apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cleanup
spec:
  steps:
    - name: cleanup
      image: alpine
      script: |
        #!/bin/sh
        echo "Cleaning up workspace..."
        rm -rf /workspace/output/* || true

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: nose
spec:
  workspaces:
    - name: source
  steps:
    - name: run-nose-tests
      image: python:3.9
      workingDir: /workspace/source
      script: |
        #!/bin/sh
        pip install nose
        echo "Running nose tests..."
        nosetests -v || true
